name: Deploy-Blog
on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

jobs:
  # 直接在jobs级别调用可复用工作流（关键！）
  call-deploy-workflow:
    uses: ./.github/workflows/reusable-workflow.yml  # 引用可复用工作流
    with:
      trigger-source: "push"  # 传递参数
    secrets: inherit  # 传递仓库密钥（如NOTION_TOKEN）