name: api手动触发
on:
  repository_dispatch:
    types:
      - deploy-trigger
      - sync-data

jobs:
  # 直接在jobs级别调用可复用工作流（关键！）
  call-deploy-workflow:
    uses: ./.github/workflows/reusable-workflow.yml  # 引用可复用工作流
    with:
      trigger-source: "api"  # 传递参数
    secrets: inherit  # 传递仓库密钥