name: api手动触发
on:
  repository_dispatch:
    types:
      - deploy-trigger  # 部署触发
      - sync-data       # 数据同步触发

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      trigger-source: "api"  # 标识触发来源为API
